name: Check Syntax

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # 最新バージョンに変更
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v4 # 最新バージョンに変更
      with:
        python-version: 3.13.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py[voice] flake8
    - name: Run flake8
      run: flake8 --ignore=E302,E501
